<template>
  <div class="page-container">
    <header class="page-header">
      <h1 class="page-title">Pengeluaran & Biaya</h1>
      <p class="page-subtitle">Kelola konfigurasi biaya operasional dan catat pengeluaran kosan Anda.</p>
    </header>

    <div class="material-card" style="margin-bottom: 2rem;">
      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1.25rem;">
        <h2 style="color: var(--primary-color); margin: 0;">Konfigurasi Biaya Pengeluaran</h2>
        <button class="btn" @click="openConfigModal()">+ Tambah Konfigurasi</button>
      </div>

      <div class="table-container">
        <table class="data-table">
          <thead>
            <tr>
              <th>Jenis Iuran</th>
              <th>Nominal (Rp)</th>
              <th>Frekuensi</th>
              <th>Jadwal / Durasi</th>
              <th style="text-align: right;">Aksi</th>
            </tr>
          </thead>
          <tbody>
            <tr v-if="configs.length === 0">
              <td colspan="5" style="text-align: center; color: var(--text-muted);">Belum ada konfigurasi.</td>
            </tr>
            <tr v-for="cfg in configs" :key="cfg._id">
              <td style="font-weight: 500;">{{ cfg.name }}</td>
              <td>Rp {{ cfg.amount.toLocaleString('id-ID') }}</td>
              <td>{{ cfg.frequency }}</td>
              <td>
                <span v-if="cfg.frequency === 'Manual'">-</span>
                <span v-else-if="cfg.timingType === 'Fixed' && cfg.frequency === 'Bulanan'">Setiap tanggal {{ cfg.fixedDay }}</span>
                <span v-else-if="cfg.timingType === 'Fixed' && cfg.frequency === 'Mingguan'">Hari ke-{{ cfg.fixedDay }} tiap minggu</span>
                <span v-else-if="cfg.timingType === 'Fixed' && cfg.frequency === 'Harian'">Setiap hari</span>
                <span v-else>Setiap {{ cfg.duration }} {{ cfg.frequency === 'Bulanan' ? 'Bulan' : cfg.frequency === 'Mingguan' ? 'Minggu' : 'Hari' }}</span>
              </td>
              <td style="text-align: right; display: flex; gap: 0.5rem; justify-content: flex-end;">
                <button class="btn btn-sm" style="background: #0288d1; color: white;" @click="triggerConfig(cfg._id)" :disabled="triggeringId === cfg._id">PICU / CATAT</button>
                <button class="btn btn-sm" style="background: #ed6c02; color: white;" @click="openConfigModal(cfg)">Edit</button>
                <button class="btn btn-sm" style="background: var(--danger); color: white;" @click="deleteConfig(cfg._id)">Hapus</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="material-card">
      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1.25rem;">
        <h2 style="color: var(--primary-color); margin: 0;">Riwayat Pengeluaran</h2>
        <div style="display: flex; gap: 0.5rem; align-items: center;">
          <label style="font-weight: 500;">Filter Bulan:</label>
          <input type="month" v-model="filterMonth" class="input" style="width: auto; padding: 0.25rem 0.5rem;" @change="fetchHistory" />
        </div>
      </div>
      
      <div v-if="pendingHistory">Memuat riwayat...</div>
      <div v-else class="table-container">
        <table class="data-table">
          <thead>
            <tr>
              <th>Tanggal</th>
              <th>Kategori</th>
              <th>Deskripsi</th>
              <th>Nominal (Rp)</th>
              <th>Sistem</th>
              <th style="text-align: right;">Aksi</th>
            </tr>
          </thead>
          <tbody>
            <tr v-if="history.length === 0">
              <td colspan="6" style="text-align: center; color: var(--text-muted);">Belum ada riwayat pengeluaran di bulan ini.</td>
            </tr>
            <tr v-for="h in history" :key="h._id">
              <td>{{ new Date(h.date).toLocaleDateString('id-ID') }}</td>
              <td style="font-weight: 500;">{{ h.category }}</td>
              <td>{{ h.description }}</td>
              <td>Rp {{ h.amount.toLocaleString('id-ID') }}</td>
              <td>
                <span v-if="h.isAutoGenerated" class="status-badge status-active">Otomatis (Cron)</span>
                <span v-else class="status-badge status-booked">Manual</span>
              </td>
              <td style="text-align: right;">
                <button class="btn btn-sm" style="background: var(--danger); color: white;" @click="deleteExpense(h._id)">Hapus</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- Modal Konfigurasi -->
    <div class="modal-overlay" v-if="showModal" @click.self="showModal = false">
      <div class="modal-content material-card" style="max-width: 500px; width: 100%;">
        <h2 style="margin-top: 0; color: var(--primary-color);">{{ form._id ? 'Edit' : 'Tambah' }} Konfigurasi Biaya</h2>
        
        <div style="margin-bottom: 1rem;">
          <label style="display: block; margin-bottom: 0.25rem;">Jenis Iuran / Nama Biaya</label>
          <input type="text" v-model="form.name" class="input" placeholder="Misal: Iuran Sampah, Internet" />
        </div>

        <div style="margin-bottom: 1rem;">
          <label style="display: block; margin-bottom: 0.25rem;">Nominal (Rp)</label>
          <input type="number" min="0" v-model="form.amount" class="input" />
        </div>

        <div style="margin-bottom: 1rem;">
          <label style="display: block; margin-bottom: 0.25rem;">Frekuensi</label>
          <select v-model="form.frequency" class="input">
            <option value="Manual">Manual (Hanya lewat tombol PICU)</option>
            <option value="Harian">Harian</option>
            <option value="Mingguan">Mingguan</option>
            <option value="Bulanan">Bulanan</option>
          </select>
        </div>

        <div v-if="form.frequency !== 'Manual'" style="margin-bottom: 1rem; padding: 1rem; background: #f9f9f9; border-radius: 8px;">
          <label style="display: block; margin-bottom: 0.5rem; font-weight: 500;">Opsi Penjadwalan</label>
          
          <div style="display: flex; gap: 1rem; margin-bottom: 0.75rem;">
            <label><input type="radio" v-model="form.timingType" value="Duration" /> Berdasarkan Durasi (Tiap x waktu)</label>
            <label><input type="radio" v-model="form.timingType" value="Fixed" /> Tanggal/Hari Tetap</label>
          </div>

          <div v-if="form.timingType === 'Duration'">
            <label style="display: block; margin-bottom: 0.25rem;">Setiap berapa {{ form.frequency === 'Bulanan' ? 'bulan' : form.frequency === 'Mingguan' ? 'minggu' : 'hari' }} sekali?</label>
            <input type="number" min="1" v-model="form.duration" class="input" />
          </div>

          <div v-else>
            <div v-if="form.frequency === 'Bulanan'">
              <label style="display: block; margin-bottom: 0.25rem;">Tanggal Potong (1-31)</label>
              <input type="number" min="1" max="31" v-model="form.fixedDay" class="input" />
            </div>
            <div v-else-if="form.frequency === 'Mingguan'">
              <label style="display: block; margin-bottom: 0.25rem;">Hari Potong (0 = Minggu, 1 = Senin, ... 6 = Sabtu)</label>
              <input type="number" min="0" max="6" v-model="form.fixedDay" class="input" />
            </div>
            <div v-else>
              <small class="text-muted">Akan dipotong setiap hari.</small>
            </div>
          </div>
        </div>

        <div style="display: flex; gap: 0.5rem; justify-content: flex-end; margin-top: 1.5rem;">
          <button class="btn" style="background: #e0e0e0; color: #333;" @click="showModal = false">Batal</button>
          <button class="btn" @click="saveConfig" :disabled="saving">Simpan</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';

const configs = ref<any[]>([]);
const history = ref<any[]>([]);
const filterMonth = ref('');

const pendingHistory = ref(false);
const showModal = ref(false);
const saving = ref(false);
const triggeringId = ref<string | null>(null);

const defaultForm = {
  _id: null,
  name: '',
  amount: 0,
  frequency: 'Manual',
  timingType: 'Duration',
  duration: 1,
  fixedDay: 1
};
const form = ref<any>({ ...defaultForm });

onMounted(() => {
  const d = new Date();
  filterMonth.value = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
  fetchConfigs();
  fetchHistory();
});

const fetchConfigs = async () => {
  try {
    const res = await fetch('http://localhost:3011/api/expenses/config');
    configs.value = await res.json();
  } catch (err) {
    console.error(err);
  }
};

const fetchHistory = async () => {
  pendingHistory.value = true;
  try {
    const res = await fetch(`http://localhost:3011/api/expenses?month=${filterMonth.value}`);
    history.value = await res.json();
  } catch (err) {
    console.error(err);
  }
  pendingHistory.value = false;
};

const openConfigModal = (cfg?: any) => {
  if (cfg) {
    form.value = { ...cfg };
  } else {
    form.value = { ...defaultForm };
  }
  showModal.value = true;
};

const saveConfig = async () => {
  if (!form.value.name || form.value.amount < 0) {
    alert('Mohon isi nama dan nominal yang valid.');
    return;
  }
  saving.value = true;
  try {
    let url = 'http://localhost:3011/api/expenses/config';
    let method = 'POST';
    if (form.value._id) {
      url += `/${form.value._id}`;
      method = 'PUT';
    }
    const res = await fetch(url, {
      method,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(form.value)
    });
    if (!res.ok) throw new Error('Failed to save config');
    await fetchConfigs();
    showModal.value = false;
  } catch (err) {
    alert('Gagal menyimpan konfigurasi.');
  }
  saving.value = false;
};

const deleteConfig = async (id: string) => {
  if (!confirm('Yakin ingin menghapus konfigurasi ini? Ini tidak akan menghapus riwayat pengeluarannya.')) return;
  try {
    await fetch(`http://localhost:3011/api/expenses/config/${id}`, { method: 'DELETE' });
    await fetchConfigs();
  } catch (err) {
    alert('Gagal menghapus konfigurasi.');
  }
};

const triggerConfig = async (id: string) => {
  triggeringId.value = id;
  try {
    const res = await fetch('http://localhost:3011/api/expenses/trigger', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ configId: id })
    });
    if (!res.ok) {
      const errData = await res.json();
      throw new Error(errData.error || 'Failed to trigger');
    }
    alert('Pengeluaran berhasil dicatat!');
    await fetchHistory();
  } catch (err: any) {
    alert('Gagal mencatat: ' + err.message);
  }
  triggeringId.value = null;
};

const deleteExpense = async (id: string) => {
  if (!confirm('Hapus riwayat pengeluaran ini?')) return;
  try {
    await fetch(`http://localhost:3011/api/expenses/${id}`, { method: 'DELETE' });
    await fetchHistory();
  } catch (err) {
    alert('Gagal menghapus riwayat.');
  }
};
</script>

<style scoped>
.page-container {
  padding: 2rem;
  max-width: 1200px;
  margin: 0 auto;
}

.page-header {
  margin-bottom: 2rem;
}

.page-title {
  color: var(--primary-color);
  font-size: 2rem;
  margin-bottom: 0.5rem;
}

.page-subtitle {
  color: var(--text-muted);
  font-size: 1.1rem;
}

.material-card {
  background: white;
  border-radius: 12px;
  padding: 1.5rem;
  box-shadow: 0 4px 6px rgba(0,0,0,0.05);
}

.table-container {
  overflow-x: auto;
}

.data-table {
  width: 100%;
  border-collapse: collapse;
}

.data-table th, .data-table td {
  padding: 1rem;
  text-align: left;
  border-bottom: 1px solid #eee;
}

.data-table th {
  font-weight: 600;
  color: var(--text-muted);
  background: #f9f9f9;
}

.btn {
  padding: 0.6rem 1.2rem;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  font-weight: 500;
  background: var(--primary-color);
  color: white;
  transition: opacity 0.2s;
}

.btn:hover {
  opacity: 0.9;
}

.btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.btn-sm {
  padding: 0.4rem 0.8rem;
  font-size: 0.9rem;
}

.input {
  width: 100%;
  padding: 0.6rem;
  border: 1px solid #ccc;
  border-radius: 6px;
}

.status-badge {
  padding: 0.25rem 0.5rem;
  border-radius: 12px;
  font-size: 0.85em;
  font-weight: bold;
}
.status-active { background: #e8f5e9; color: #2e7d32; }
.status-booked { background: #fff3e0; color: #ef6c00; }

.modal-overlay {
  position: fixed;
  top: 0; left: 0; right: 0; bottom: 0;
  background: rgba(0,0,0,0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}
</style>
