import mongoose, { Schema, Document } from 'mongoose';

export interface IExpense extends Document {
  category: string;
  amount: number;
  description: string;
  date: Date;
  isAutoGenerated: boolean;
  referencePeriod: string; // e.g. 'YYYY-MM-DD', 'YYYY-Wxx', 'YYYY-MM' to prevent duplicate cuts
  configId?: mongoose.Types.ObjectId;
}

const ExpenseSchema: Schema = new Schema({
  category: { type: String, required: true },
  amount: { type: Number, required: true },
  description: { type: String, default: '' },
  date: { type: Date, default: Date.now },
  isAutoGenerated: { type: Boolean, default: false },
  referencePeriod: { type: String },
  configId: { type: Schema.Types.ObjectId, ref: 'ExpenseConfig' }
}, { timestamps: true });

export default mongoose.model<IExpense>('Expense', ExpenseSchema);
