import ExpenseConfig, { IExpenseConfig } from '../models/ExpenseConfig';
import Expense from '../models/Expense';
import Room from '../models/Room';
import mongoose from 'mongoose';

export const processAutomatedExpenses = async () => {
  try {
    const today = new Date();
    const currentYear = today.getFullYear();
    const currentMonthNum = today.getMonth() + 1;
    const currentDay = today.getDate();
    const currentDayOfWeek = today.getDay(); // 0-6 (Sun-Sat)

    const configs = await ExpenseConfig.find({ frequency: { $ne: 'Manual' } });

    for (const config of configs) {
      let isDue = false;
      let referencePeriod = '';

      if (config.frequency === 'Harian') {
        referencePeriod = `${currentYear}-${String(currentMonthNum).padStart(2, '0')}-${String(currentDay).padStart(2, '0')}`;
        if (config.timingType === 'Fixed') {
          // If Fixed timingType for Harian, it runs every day anyway.
          isDue = true;
        } else {
          // Duration e.g. every 2 days. For simplicity we check if duration days passed since last cut.
          // Since we don't store last run on config, we just run daily if duration=1. If duration>1, we could check modulo.
          // For simplicity, Harian Duration=X will trigger every X days from epoch.
          const epochDays = Math.floor(today.getTime() / (1000 * 60 * 60 * 24));
          if (epochDays % (config.duration || 1) === 0) {
            isDue = true;
          }
        }
      } else if (config.frequency === 'Mingguan') {
        const weekNum = getWeekNumber(today);
        referencePeriod = `${currentYear}-W${String(weekNum).padStart(2, '0')}`;
        
        if (config.timingType === 'Fixed') {
          // fixedDay 0-6 (Sun-Sat)
          if (currentDayOfWeek === config.fixedDay) {
            isDue = true;
          }
        } else {
          // Duration e.g. every 1 week. Check if we already cut this week.
          isDue = true; 
        }
      } else if (config.frequency === 'Bulanan') {
        referencePeriod = `${currentYear}-${String(currentMonthNum).padStart(2, '0')}`;
        
        if (config.timingType === 'Fixed') {
          // fixedDay 1-31
          const lastDayOfMonth = new Date(currentYear, currentMonthNum, 0).getDate();
          const targetDay = Math.min(config.fixedDay, lastDayOfMonth);
          if (currentDay === targetDay) {
            isDue = true;
          }
        } else {
          // Duration e.g. every 1 month. We just trigger it once this month. 
          // (Can happen any day, but typically cron runs daily, so it triggers on 1st).
          if (currentMonthNum % (config.duration || 1) === 0 && currentDay === 1) {
             isDue = true;
          }
        }
      }

      if (isDue) {
        await executeConfig(config, referencePeriod, true);
      }
    }
  } catch (err) {
    console.error('Failed to generate recurring expenses:', err);
  }
};

export const executeConfig = async (config: IExpenseConfig, referencePeriod: string, isAuto: boolean) => {
  // Check if already executed for this period to prevent duplicates
  const existing = await Expense.findOne({ configId: config._id, referencePeriod, isAutoGenerated: isAuto });
  if (existing && isAuto) {
    return false; // Already auto-generated this period
  }

  let finalAmount = config.amount;
  let desc = `${isAuto ? 'Auto-generated' : 'Manual'} expense for ${config.name}`;

  // Legacy fallback support for Listrik per room multiplier, although we now just use fixed amount
  if (config.name === 'Listrik' || config.name.toLowerCase().includes('per kamar')) {
     // If we wanted dynamic multiplier based on rooms we could add it here
  }

  await Expense.create({
    category: config.name,
    amount: finalAmount,
    description: desc,
    date: new Date(),
    isAutoGenerated: isAuto,
    referencePeriod,
    configId: config._id
  });

  return true;
}

// Utility for week number
function getWeekNumber(d: Date) {
  const dCopy = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
  const dayNum = dCopy.getUTCDay() || 7;
  dCopy.setUTCDate(dCopy.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(dCopy.getUTCFullYear(),0,1));
  return Math.ceil((((dCopy.getTime() - yearStart.getTime()) / 86400000) + 1)/7);
}

// Legacy function to maintain dashboard route compatibility without crashing
export const generateRecurringExpenses = async () => {
  // We can let this be a no-op since Cron will handle it, or we can trigger it too.
  // The user requested cron, so we'll leave dashboard as a fallback that can safely run.
  await processAutomatedExpenses();
};
