import { Router, Request, Response } from 'express';
import ExpenseConfig from '../models/ExpenseConfig';
import Expense from '../models/Expense';
import { executeConfig } from '../services/expenseGenerator';
import mongoose from 'mongoose';

const router = Router();

// ==========================================
// CONFIGURATION (ExpenseItemConfig)
// ==========================================

// Get all configs
router.get('/config', async (req: Request, res: Response) => {
  try {
    const configs = await ExpenseConfig.find();
    res.json(configs);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Add new config
router.post('/config', async (req: Request, res: Response) => {
  try {
    const config = await ExpenseConfig.create(req.body);
    res.status(201).json(config);
  } catch (err: any) {
    res.status(400).json({ error: err.message });
  }
});

// Update config
router.put('/config/:id', async (req: Request, res: Response) => {
  try {
    const config = await ExpenseConfig.findByIdAndUpdate(req.params.id, req.body, { new: true });
    if (!config) {
       res.status(404).json({ error: 'Config not found' });
       return;
    }
    res.json(config);
  } catch (err: any) {
    res.status(400).json({ error: err.message });
  }
});

// Delete config
router.delete('/config/:id', async (req: Request, res: Response) => {
  try {
    await ExpenseConfig.findByIdAndDelete(req.params.id);
    res.json({ message: 'Config deleted' });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// ==========================================
// EXPENSE RECORDS
// ==========================================

// Get expenses for a specific month (YYYY-MM)
router.get('/', async (req: Request, res: Response) => {
  try {
    const month = req.query.month as string;
    const query = month ? { referencePeriod: { $regex: `^${month}` } } : {};
    const expenses = await Expense.find(query).sort({ date: -1 });
    res.json(expenses);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Add completely manual one-off expense (no config attached)
router.post('/', async (req: Request, res: Response) => {
  try {
    const expense = new Expense({
      ...req.body,
      isAutoGenerated: false
    });
    const d = new Date(expense.date || Date.now());
    expense.referencePeriod = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
    
    await expense.save();
    res.status(201).json(expense);
  } catch (err: any) {
    res.status(400).json({ error: err.message });
  }
});

// Trigger a configured expense manually
router.post('/trigger', async (req: Request, res: Response) => {
  try {
    const { configId } = req.body;
    
    if (!configId) {
       res.status(400).json({ error: 'configId is required' });
       return;
    }

    const config = await ExpenseConfig.findById(configId);
    if (!config) {
       res.status(404).json({ error: 'Config not found' });
       return;
    }

    const today = new Date();
    // Default manual trigger attaches to current month for simplicity
    const currentPeriod = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-MANUAL`;

    const success = await executeConfig(config, currentPeriod, false);

    if (success) {
      res.json({ message: `${config.name} berhasil dicatat.` });
    } else {
      res.status(400).json({ error: 'Gagal mencatat pengeluaran.' });
    }
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Delete expense
router.delete('/:id', async (req: Request, res: Response) => {
  try {
    await Expense.findByIdAndDelete(req.params.id);
    res.json({ message: 'Expense deleted' });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

export default router;
